### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by IanYeung** [YapengTian/TDAN_VSR#4]
https://github.com/YapengTian/TDAN_VSR/blob/c00b8d15f91fbf652102c9fd21c247cdfdbe6e21/model.py#L76-L78

Isn't it the feature aligned in line 76? Why you need to further pass through another deformable convolution layer in line 78?

**Comment by YapengTian** [comment]
Yes, the features from the deconv_3 in line 76 are aligned features. To further enhance transformation capacity and explore more contexture information for reconstructing the target aligned pixels (the predicted offsets will flexibly enlarge receptive field), we use additional regular deformable convolution layers (not for temporal alignment as the layer: deconv_3).

**Comment by IanYeung** [comment]
Thanks for your quick response.
