### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by HarukiYqM** [YapengTian/TDAN_VSR#5]
When I read the paper, I noticed that the PSNR reported in BD setting is better than BI setting in Vid4. It's pretty strange as BD contains degradation process.  Are you sure for this? and do you have any insights about this?

**Comment by YapengTian** [comment]
We found that our BI model can be further improved. But, it seems that BD model is still better. A similar observation is also shown in the SIS-RDN paper. With a blurring kernel, the aliasing artifacts will be reduced during downsampling. Actually, you could try LR images from directly sampling (nearest sampling), then you might find that the SR results would be worse than results from bicubic sampling, which also has a smoothing kernel implemented in Matlab.

**Comment by HarukiYqM** [comment]
Thanks for your reply! Can I ask a few more question? I wonder what is the kernel size for your BD settings and does it mean you apply BD settings to create input when you test Vid4?

**Comment by YapengTian** [comment]
I used the BD resizing code from the RDN https://github.com/yulunzhang/RDN/blob/master/RDN_IR/RDN_TestCode/RDN_SR_RGB/Prepare_TestData_HR_LR.m.

**Comment by HarukiYqM** [comment]
thanks a lot!
