### ISSUE TITLE
about size and standard deviation of gaussian filter in BD degradation

### ISSUE THREAD

**Issue by duck9144** [YapengTian/TDAN_VSR#7]
Hi! I‘m use the same database vimeo-90k for VSR. Could you tell me the size and standard deviation of gaussian filter in your paper?

**Comment by YapengTian** [comment]
I used the BD resizing code from the RDN https://github.com/yulunzhang/RDN/blob/master/RDN_IR/RDN_TestCode/RDN_SR_RGB/Prepare_TestData_HR_LR.m.

**Comment by duck9144** [comment]
Thank you so much!^^
